<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>LogWatcher.Common</RootNamespace>
    <AssemblyName>LogWatcher.Common</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.configuration" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="WeifenLuo.WinFormsUI.Docking">
      <HintPath>..\WeifenLuo.WinFormsUI.Docking.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
